name: ctta
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - colorama=0.4.4
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.3.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - appdirs==1.4.4
      - attr==0.3.1
      - attrs==21.2.0
      - autoattack==0.1
      - backcall==0.2.0
      - black==19.3b0
      - braceexpand==0.1.7
      - cffi==1.16.0
      - chardet==3.0.4
      - charset-normalizer==3.3.0
      - click==8.0.3
      - cloudpickle==2.0.0
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==41.0.4
      - cycler==0.11.0
      - decorator==5.1.0
      - docker-pycreds==0.4.0
      - einops==0.4.1
      - filelock==3.12.2
      - flake8==4.0.1
      - fonttools==4.42.0
      - fsspec==2023.6.0
      - fvcore==0.1.6
      - gitdb==4.0.10
      - gitpython==3.1.32
      - googledrivedownloader==0.4
      - huggingface-hub==0.16.4
      - idna==2.10
      - imagecorruptions==1.1.2
      - imageio==2.10.1
      - iopath==0.1.9
      - ipython==7.28.0
      - isort==4.3.21
      - jedi==0.18.0
      - jinja2==2.11.3
      - jmespath==0.10.0
      - joblib==1.1.0
      - kiwisolver==1.4.4
      - kornia==0.6.8
      - markdown-it-py==3.0.0
      - markupsafe==2.0.1
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.3
      - mccabe==0.6.1
      - mdurl==0.1.2
      - networkx==2.6.3
      - numpy==1.19.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - opencv-python==4.8.0.76
      - oss2==2.17.0
      - packaging==21.0
      - pandas==1.1.5
      - parameterized==0.8.1
      - parso==0.8.2
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - portalocker==2.3.2
      - promise==2.3
      - prompt-toolkit==3.0.21
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pycodestyle==2.8.0
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pyflakes==2.4.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorchcv==0.0.67
      - pytz==2023.3.post1
      - pywavelets==1.1.1
      - pyyaml==6.0
      - requests==2.23.0
      - rich==13.4.2
      - robustbench==0.1
      - scikit-image==0.18.3
      - scikit-learn==1.0.1
      - scipy==1.9.3
      - seaborn==0.12.2
      - sentry-sdk==1.9.0
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - shortuuid==1.0.11
      - simplejson==3.17.5
      - smmap==5.0.0
      - submitit==1.4.0
      - tabulate==0.9.0
      - termcolor==2.3.0
      - threadpoolctl==3.0.0
      - tifffile==2021.10.12
      - timm==0.6.13
      - toml==0.10.2
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchcam==0.3.2
      - torchvision==0.14.1
      - tqdm==4.56.2
      - traitlets==5.1.0
      - urllib3==1.25.11
      - wandb==0.12.17
      - wcwidth==0.2.5
      - webdataset==0.2.86
      - yacs==0.1.8
      - yapf==0.31.0
      - yattag==1.14.0
